# Generated by Django 2.2.3 on 2019-08-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llave',
            name='acceso_ilimitado',
            field=models.BooleanField(default=False),
        ),
    ]
