# Generated by Django 2.2.3 on 2019-07-17 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_llave_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='llave',
            old_name='estado',
            new_name='revocada',
        ),
    ]
