# Generated by Django 2.2.3 on 2019-07-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20190717_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llave',
            name='revocada',
            field=models.BooleanField(default=True),
        ),
    ]
