# Generated by Django 2.2.3 on 2019-07-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llave',
            name='revocada',
            field=models.BooleanField(default=False),
        ),
    ]
