# Generated by Django 2.2.3 on 2019-07-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_registro_llave'),
    ]

    operations = [
        migrations.AddField(
            model_name='llave',
            name='correo',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
