# Generated by Django 2.2.3 on 2019-08-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0010_dispositivo_numero_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='llave',
            name='codigo',
            field=models.CharField(default='', max_length=20),
        ),
    ]
