# Generated by Django 2.2.3 on 2019-08-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0012_auto_20190805_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='numero_serie',
            field=models.CharField(default='', max_length=10),
        ),
    ]
