# Generated by Django 2.2.3 on 2019-08-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0014_sesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='llave',
            name='es_dueno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='llave',
            name='es_multiuso',
            field=models.BooleanField(default=True),
        ),
    ]
