# Generated by Django 2.2.3 on 2019-08-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0015_auto_20190814_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llave',
            name='fecha_expiracion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='llave',
            name='fecha_inicio',
            field=models.DateTimeField(null=True),
        ),
    ]
